ipc = on

# дефолт на случай отсутствия сохранённого выбора
wallpaper {
    monitor = eDP-2
    path = ~/Pictures/Wallpapers/wall.png
    fit_mode = cover
}

# последний выбранный (перезаписывает дефолт, если файл существует)
source = ~/.cache/hypr/current-wall.conf
